SHELL := /bin/bash

# base command
PHOTOS_CMD := photos -base .

# list of jpeg sizes
SIZES := 3840,1920

# size to upload to Google Photos (one of SIZES)
GPhotoSize := 3840

# size to symlink to Flat (one of SIZES)
FlatSize := 3840

# only images with a rating > $(RatingGT) will be converted
RatingGT := 2

include photos.mk
