SHELL := /bin/bash

# base command
PHOTOS_CMD := photos -base .

# list of jpeg sizes
SIZES := 3840,1920

# size to use for GPhotos symlinks
GPhotoSize := 3840

# only images with a rating > $(RatingGT) will be converted
RatingGT := 2

include photos.mk
